### ISSUE TITLE
Support of async and await

### ISSUE THREAD

**Issue by Exti** [HerrLoesch/DynamicSpecs#19] opened 2017-01-25 14:38 UTC
At the moment it is possible to use async and await in the test methods. But in Given(), and When() it is currently not supported (it will not wait).

Please can you add this feature?

Thanks Andreas

**Comment by Exti** [comment] 2017-01-25 14:41
Oh - I found the Issue "Provide asyncronouse Given and When methods.", so my request is a dublicate.

**Comment by HerrLoesch** [comment] 2017-02-22 08:28
Duplicate of #4

**Closed as completed** 2017-02-22 08:28 UTC
Labels: duplicate
